
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module SoCKit_freedom(

	//////////// CLOCK //////////
	OSC_50_B3B,
	OSC_50_B4A,
	OSC_50_B5B,
	OSC_50_B8A,

	//////////// LED //////////
	LED,

	//////////// KEY //////////
	KEY,
	RESET_n,

	//////////// Si5338 //////////
	SI5338_SCL,
	SI5338_SDA,

	//////////// Temperature //////////
	TEMP_CS_n,
	TEMP_DIN,
	TEMP_DOUT,
	TEMP_SCLK,

	//////////// SDRAM //////////
	DDR3_A,
	DDR3_BA,
	DDR3_CAS_n,
	DDR3_CK_n,
	DDR3_CK_p,
	DDR3_CKE,
	DDR3_CS_n,
	DDR3_DM,
	DDR3_DQ,
	DDR3_DQS_n,
	DDR3_DQS_p,
	DDR3_ODT,
	DDR3_RAS_n,
	DDR3_RESET_n,
	DDR3_RZQ,
	DDR3_WE_n,

	//////////// HSMC, HSMC connect to HSMC Default //////////
	HSMC_CLK_IN0,
	HSMC_CLK_OUT0,
	HSMC_CLKIN_N,
	HSMC_CLKIN_P,
	HSMC_CLKOUT_N,
	HSMC_CLKOUT_P,
	HSMC_D,
	HSMC_GXB_RX_P,
	HSMC_GXB_TX_P,
	HSMC_RX_N,
	HSMC_RX_P,
	HSMC_SCL,
	HSMC_SDA,
	HSMC_TX_N,
	HSMC_TX_P 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		OSC_50_B3B;
input 		          		OSC_50_B4A;
input 		          		OSC_50_B5B;
input 		          		OSC_50_B8A;

//////////// LED //////////
output		     [3:0]		LED;

//////////// KEY //////////
input 		     [3:0]		KEY;
input 		          		RESET_n;

//////////// Si5338 //////////
output		          		SI5338_SCL;
inout 		          		SI5338_SDA;

//////////// Temperature //////////
output		          		TEMP_CS_n;
output		          		TEMP_DIN;
input 		          		TEMP_DOUT;
output		          		TEMP_SCLK;

//////////// SDRAM //////////
output		    [14:0]		DDR3_A;
output		     [2:0]		DDR3_BA;
output		          		DDR3_CAS_n;
output		          		DDR3_CK_n;
output		          		DDR3_CK_p;
output		          		DDR3_CKE;
output		          		DDR3_CS_n;
output		     [3:0]		DDR3_DM;
inout 		    [31:0]		DDR3_DQ;
inout 		     [3:0]		DDR3_DQS_n;
inout 		     [3:0]		DDR3_DQS_p;
output		          		DDR3_ODT;
output		          		DDR3_RAS_n;
output		          		DDR3_RESET_n;
input 		          		DDR3_RZQ;
output		          		DDR3_WE_n;

//////////// HSMC, HSMC connect to HSMC Default //////////
input 		          		HSMC_CLK_IN0;
output		          		HSMC_CLK_OUT0;
input 		     [2:1]		HSMC_CLKIN_N;
input 		     [2:1]		HSMC_CLKIN_P;
output		     [2:1]		HSMC_CLKOUT_N;
output		     [2:1]		HSMC_CLKOUT_P;
inout 		     [3:0]		HSMC_D;
input 		     [7:0]		HSMC_GXB_RX_P;
output		     [7:0]		HSMC_GXB_TX_P;
inout 		    [16:0]		HSMC_RX_N;
inout 		    [16:0]		HSMC_RX_P;
output		          		HSMC_SCL;
inout 		          		HSMC_SDA;
inout 		    [16:0]		HSMC_TX_N;
inout 		    [16:0]		HSMC_TX_P;


//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



endmodule
