	DDR3AXI4 u0 (
		.afi_clk_clk                           (<connected-to-afi_clk_clk>),                           //           afi_clk.clk
		.afi_reset_reset_n                     (<connected-to-afi_reset_reset_n>),                     //         afi_reset.reset_n
		.axi_translator_s0_awid                (<connected-to-axi_translator_s0_awid>),                // axi_translator_s0.awid
		.axi_translator_s0_awaddr              (<connected-to-axi_translator_s0_awaddr>),              //                  .awaddr
		.axi_translator_s0_awlen               (<connected-to-axi_translator_s0_awlen>),               //                  .awlen
		.axi_translator_s0_awsize              (<connected-to-axi_translator_s0_awsize>),              //                  .awsize
		.axi_translator_s0_awburst             (<connected-to-axi_translator_s0_awburst>),             //                  .awburst
		.axi_translator_s0_awlock              (<connected-to-axi_translator_s0_awlock>),              //                  .awlock
		.axi_translator_s0_awcache             (<connected-to-axi_translator_s0_awcache>),             //                  .awcache
		.axi_translator_s0_awprot              (<connected-to-axi_translator_s0_awprot>),              //                  .awprot
		.axi_translator_s0_awqos               (<connected-to-axi_translator_s0_awqos>),               //                  .awqos
		.axi_translator_s0_awvalid             (<connected-to-axi_translator_s0_awvalid>),             //                  .awvalid
		.axi_translator_s0_awready             (<connected-to-axi_translator_s0_awready>),             //                  .awready
		.axi_translator_s0_wdata               (<connected-to-axi_translator_s0_wdata>),               //                  .wdata
		.axi_translator_s0_wstrb               (<connected-to-axi_translator_s0_wstrb>),               //                  .wstrb
		.axi_translator_s0_wlast               (<connected-to-axi_translator_s0_wlast>),               //                  .wlast
		.axi_translator_s0_wvalid              (<connected-to-axi_translator_s0_wvalid>),              //                  .wvalid
		.axi_translator_s0_wready              (<connected-to-axi_translator_s0_wready>),              //                  .wready
		.axi_translator_s0_bid                 (<connected-to-axi_translator_s0_bid>),                 //                  .bid
		.axi_translator_s0_bresp               (<connected-to-axi_translator_s0_bresp>),               //                  .bresp
		.axi_translator_s0_bvalid              (<connected-to-axi_translator_s0_bvalid>),              //                  .bvalid
		.axi_translator_s0_bready              (<connected-to-axi_translator_s0_bready>),              //                  .bready
		.axi_translator_s0_arid                (<connected-to-axi_translator_s0_arid>),                //                  .arid
		.axi_translator_s0_araddr              (<connected-to-axi_translator_s0_araddr>),              //                  .araddr
		.axi_translator_s0_arlen               (<connected-to-axi_translator_s0_arlen>),               //                  .arlen
		.axi_translator_s0_arsize              (<connected-to-axi_translator_s0_arsize>),              //                  .arsize
		.axi_translator_s0_arburst             (<connected-to-axi_translator_s0_arburst>),             //                  .arburst
		.axi_translator_s0_arlock              (<connected-to-axi_translator_s0_arlock>),              //                  .arlock
		.axi_translator_s0_arcache             (<connected-to-axi_translator_s0_arcache>),             //                  .arcache
		.axi_translator_s0_arprot              (<connected-to-axi_translator_s0_arprot>),              //                  .arprot
		.axi_translator_s0_arqos               (<connected-to-axi_translator_s0_arqos>),               //                  .arqos
		.axi_translator_s0_arvalid             (<connected-to-axi_translator_s0_arvalid>),             //                  .arvalid
		.axi_translator_s0_arready             (<connected-to-axi_translator_s0_arready>),             //                  .arready
		.axi_translator_s0_rid                 (<connected-to-axi_translator_s0_rid>),                 //                  .rid
		.axi_translator_s0_rdata               (<connected-to-axi_translator_s0_rdata>),               //                  .rdata
		.axi_translator_s0_rresp               (<connected-to-axi_translator_s0_rresp>),               //                  .rresp
		.axi_translator_s0_rlast               (<connected-to-axi_translator_s0_rlast>),               //                  .rlast
		.axi_translator_s0_rvalid              (<connected-to-axi_translator_s0_rvalid>),              //                  .rvalid
		.axi_translator_s0_rready              (<connected-to-axi_translator_s0_rready>),              //                  .rready
		.clk_clk                               (<connected-to-clk_clk>),                               //               clk.clk
		.mem_mem_a                             (<connected-to-mem_mem_a>),                             //               mem.mem_a
		.mem_mem_ba                            (<connected-to-mem_mem_ba>),                            //                  .mem_ba
		.mem_mem_ck                            (<connected-to-mem_mem_ck>),                            //                  .mem_ck
		.mem_mem_ck_n                          (<connected-to-mem_mem_ck_n>),                          //                  .mem_ck_n
		.mem_mem_cke                           (<connected-to-mem_mem_cke>),                           //                  .mem_cke
		.mem_mem_cs_n                          (<connected-to-mem_mem_cs_n>),                          //                  .mem_cs_n
		.mem_mem_dm                            (<connected-to-mem_mem_dm>),                            //                  .mem_dm
		.mem_mem_ras_n                         (<connected-to-mem_mem_ras_n>),                         //                  .mem_ras_n
		.mem_mem_cas_n                         (<connected-to-mem_mem_cas_n>),                         //                  .mem_cas_n
		.mem_mem_we_n                          (<connected-to-mem_mem_we_n>),                          //                  .mem_we_n
		.mem_mem_reset_n                       (<connected-to-mem_mem_reset_n>),                       //                  .mem_reset_n
		.mem_mem_dq                            (<connected-to-mem_mem_dq>),                            //                  .mem_dq
		.mem_mem_dqs                           (<connected-to-mem_mem_dqs>),                           //                  .mem_dqs
		.mem_mem_dqs_n                         (<connected-to-mem_mem_dqs_n>),                         //                  .mem_dqs_n
		.mem_mem_odt                           (<connected-to-mem_mem_odt>),                           //                  .mem_odt
		.oct_rzqin                             (<connected-to-oct_rzqin>),                             //               oct.rzqin
		.pll_sharing_pll_mem_clk               (<connected-to-pll_sharing_pll_mem_clk>),               //       pll_sharing.pll_mem_clk
		.pll_sharing_pll_write_clk             (<connected-to-pll_sharing_pll_write_clk>),             //                  .pll_write_clk
		.pll_sharing_pll_locked                (<connected-to-pll_sharing_pll_locked>),                //                  .pll_locked
		.pll_sharing_pll_write_clk_pre_phy_clk (<connected-to-pll_sharing_pll_write_clk_pre_phy_clk>), //                  .pll_write_clk_pre_phy_clk
		.pll_sharing_pll_addr_cmd_clk          (<connected-to-pll_sharing_pll_addr_cmd_clk>),          //                  .pll_addr_cmd_clk
		.pll_sharing_pll_avl_clk               (<connected-to-pll_sharing_pll_avl_clk>),               //                  .pll_avl_clk
		.pll_sharing_pll_config_clk            (<connected-to-pll_sharing_pll_config_clk>),            //                  .pll_config_clk
		.pll_sharing_pll_mem_phy_clk           (<connected-to-pll_sharing_pll_mem_phy_clk>),           //                  .pll_mem_phy_clk
		.pll_sharing_afi_phy_clk               (<connected-to-pll_sharing_afi_phy_clk>),               //                  .afi_phy_clk
		.pll_sharing_pll_avl_phy_clk           (<connected-to-pll_sharing_pll_avl_phy_clk>),           //                  .pll_avl_phy_clk
		.reset_reset_n                         (<connected-to-reset_reset_n>)                          //             reset.reset_n
	);

